default_settings: null
behaviors:
  BasicEnemyAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 5
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 512
          num_layers: 5
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 1000000
    time_horizon: 32
    summary_freq: 25000
    threaded: false
    self_play: null
    behavioral_cloning: null 