default_settings: null
behaviors:
  LevelManager:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 30720
      learning_rate: 0.005
      beta: 0.02
      epsilon: 0.5
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 512
          num_layers: 5
          vis_encode_type: simple 
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 250000
    max_steps: 1500000
    time_horizon: 128  
    summary_freq: 25000 
    threaded: false